version: "3.9"

services:
  redis:
    image: redis:7
    ports: ["6379:6379"]

  gateway:
    build: ..
    command: uvicorn src.api_gateway.main:app --host 0.0.0.0 --port 8000
    volumes: ["../:/app"]
    depends_on: [redis]
    environment:
      - REDIS_URL=redis://redis:6379/0

  worker_cpu:
    build: ..
    command: python -m src.workers.worker_default
    volumes: ["../:/app"]
    depends_on: [redis]
    environment:
      - REDIS_URL=redis://redis:6379/0

  worker_gpu:
    build: ..
    command: python -m src.workers.worker_gpu
    volumes: ["../:/app"]
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    depends_on: [redis]
    environment:
      - REDIS_URL=redis://redis:6379/0
